# Generated by Django 3.1.1 on 2020-09-07 08:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passwords',
            new_name='Detail',
        ),
    ]
